export const SET_INPUT = 'SET_INPUT';
export const ADD_TO_TABLE='ADD_TO_TABLE';
export const EDIT_ROW_SUCCEEDED = 'EDIT_ROW_SUCCEEDED';
export const ADD_ROW_SUCCEEDED = 'ADD_ROW_SUCCEEDED';
export const INIT_ROWS_SUCCEEDED = 'INIT_ROWS_SUCCEEDED';
export const DELETE_ROW_SUCCEEDED = 'DELETE_ROW_SUCCEEDED';
export const ADD_INPUT = 'ADD_INPUT';
export const REMOVE_INPUT = 'REMOVE_INPUT';
